version: 2.1

commands:
  echo-diff:
    steps:
      - checkout
      - run: npx turbo run build --filter='...^[2077e102987675fd2f39d7bec49d251e5eeccf70]' --dry-run=json

jobs:
  build:
    docker:
      - image: cimg/node:17.1.0
    steps:
      - echo-diff
