version: 2.1

orbs:
  jq: circleci/jq@2.2.0

commands:
  echo-diff:
    steps:
      - checkout
      - run: npx turbo run build --filter='...^[HEAD^]' --dry-run=json'
      - run: npx turbo run build --filter='...^[HEAD^]' --dry-run=json | jq '.packages'

jobs:
  build:
    docker:
      - image: cimg/node:17.1.0
    steps:
      - echo-diff
