version: 2.1

commands:
  echo-diff:
    steps:
      - checkout
      - run: yarn build --filter='...[HEAD^]' --dry-run=json

jobs:
  build:
    docker:
      - image: cimg/node:17.1.0
    steps:
      - echo-diff
